version: "3.8"

services:
  fhir-server:
    image: fhir-server:latest
    network_mode: host
    build:
      context: ./entrepot_fhir/hapi-fhir-jpaserver-starter-master
      dockerfile: Dockerfile
    volumes:
      - ./entrepot_fhir/database:/target/database:Z

  api-converter:
    image: api-converter:latest
    network_mode: host
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - FHIR_SERVER_URL=http://127.0.0.1:8080/fhir
      - EDS_DIR=/app/eds
      - OUTPUT_DIR=/app/output_export
      - REPORTS_DIR_EXPORT=/app/data/reports_export
    volumes:
      - ./eds:/app/eds:Z
    #  - ./data/reports:/app/data/reports:Z
    #  - ./data/reports_export:/app/data/reports_export/:Z
    #  - ./exports_eds_fhir:/app/output_export:Z
    #  - ./exports_eds_fhir_zip:/app/output_export_zip:Z
      - .:/app:Z
    depends_on:
      - fhir-server

networks:
  default:
    external: true
    name: host
